Repository replicatedhq/oh-my-replicated, pull requests merged in 2023-07, with the labels that each got.

#15 enable nested virtualization support by default
  replicated-gcommands/replicated-gcommands.plugin.zsh
Labels: type::feature

#13 Add script for creating and configuring a k8s VM
  Readme.md
  scripts/Readme.md
  scripts/dev_vm.sh
Labels: type::chore

#14 fix: use newest matching image
  replicated-gcommands/replicated-gcommands.plugin.zsh
Labels: bug::normal, type::bug

#11 Readme: adding a way to use the replicated-gcommands without oh-my-zsh
  Readme.md
Labels: type::docs, type::feature
